### PR TITLE
Fix multiple tests failing in all brand release PRs cypress tests and matrix workflows.

### PR DESCRIPTION
**Pull request by sangeetha-nayak**
## Proposed changes

1. Update utm_medium param value to crazy_plugin 
2. Skip Razorpay payment processor connection test for CD brand since Razorpay is not supported for the same.
3. Fix migration tests failing in some cypress matrix combinations of BH Release PR

Detailed description of failures and their fixes can be found in JIRA: [PRESS0-1673](https://jira.newfold.com/browse/PRESS0-1673)

## Type of Change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [x] Linting and tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sangeetha-nayak** [comment]
@circlecube we might not see CD tests passing here, once we create a PR to plugin we should be seeing the test pass.

**Review by circlecube — DISMISSED** [review]
This should work, but it would be more stable to use `contain` rather than `equal` for the URL check. That way we can check that it contains `https://my.yoast.com/signup?redirect_to=https://academy.yoast.com/courses/` and not worry about the rest of the params per brand.

Would also prefer to include a comment about why a test is being skipped. When we look at this later it will be good to know why the skip is in place for CD. We should always be clear why it is skipped so we can unskip it if that condition is no longer relevant.

**Comment by sangeetha-nayak** [comment]
Added possible solutions for multiple issues described here [PRESS0-1673](https://jira.newfold.com/browse/PRESS0-1673) .

**Review by krsomayagi — CHANGES_REQUESTED** [review]
Looks fine

**Review by krsomayagi — APPROVED** [review]

**Pull request merged**
